let rel = [
    {"js": " 0", "hid": "0x00", "info": "That key has no keycode"},
    {"js": " 3", "hid": "Unknown", "info": "break"},
    {"js": " 8", "hid": "0x2A", "info": "backspace / delete"},
    {"js": " 9", "hid": "0x2B", "info": "tab"},
    {"js": " 12", "hid": "0x9C", "info": "clear"},
    {"js": " 13", "hid": "0x28", "info": "enter"},
    {"js": " 16", "hid": "0xE1", "info": "shift"},
    {"js": " 17", "hid": "0xE0", "info": "ctrl"},
    {"js": " 18", "hid": "0xE2", "info": "alt"},
    {"js": " 19", "hid": "0x48", "info": "pause/break"},
    {"js": " 20", "hid": "0x82", "info": "caps lock"},
    {"js": " 21", "hid": "0x90", "info": "hangul"},
    {"js": " 25", "hid": "0x91", "info": "hanja"},
    {"js": " 27", "hid": "0x29", "info": "escape"},
    {"js": " 28", "hid": "Unknown", "info": "conversion"},
    {"js": " 29", "hid": "Unknown", "info": "non-conversion"},
    {"js": " 32", "hid": "0x2C", "info": "spacebar"},
    {"js": " 33", "hid": "0x4B", "info": "page up"},
    {"js": " 34", "hid": "0x4E", "info": "page down"},
    {"js": " 35", "hid": "0x4D", "info": "end"},
    {"js": " 36", "hid": "0x4A", "info": "home"},
    {"js": " 37", "hid": "0x50", "info": "left arrow"},
    {"js": " 38", "hid": "0x52", "info": "up arrow"},
    {"js": " 39", "hid": "0x4F", "info": "right arrow"},
    {"js": " 40", "hid": "0x51", "info": "down arrow"},
    {"js": " 41", "hid": "0x77", "info": "select"},
    {"js": " 42", "hid": "0x46", "info": "print"},
    {"js": " 43", "hid": "0x74", "info": "execute"},
    {"js": " 44", "hid": "0x46", "info": "Print Screen"},
    {"js": " 45", "hid": "0x49", "info": "insert"},
    {"js": " 46", "hid": "0x4C", "info": "delete"},
    {"js": " 47", "hid": "0x75", "info": "help"},
    {"js": " 48", "hid": "0x27", "info": "0"},
    {"js": " 49", "hid": "0x1E", "info": "1"},
    {"js": " 50", "hid": "0x1F", "info": "2"},
    {"js": " 51", "hid": "0x20", "info": "3"},
    {"js": " 52", "hid": "0x21", "info": "4"},
    {"js": " 53", "hid": "0x22", "info": "5"},
    {"js": " 54", "hid": "0x23", "info": "6"},
    {"js": " 55", "hid": "0x24", "info": "7"},
    {"js": " 56", "hid": "0x25", "info": "8"},
    {"js": " 57", "hid": "0x26", "info": "9"},
    {"js": " 58", "hid": "0x33", "info": ":"},
    {"js": " 59", "hid": "0x33", "info": "semicolon (firefox), equals"},
    {"js": " 60", "hid": "0x36", "info": "<"},
    {"js": " 61", "hid": "0x2E", "info": "equals (firefox)"},
    {"js": " 63", "hid": "Unknown", "info": "ß"},
    {"js": " 64", "hid": "0x1F", "info": "@ (firefox)"},
    {"js": " 65", "hid": "0x14", "info": "a(0x04) -> q(0x14)"},
    {"js": " 66", "hid": "0x05", "info": "b"},
    {"js": " 67", "hid": "0x06", "info": "c"},
    {"js": " 68", "hid": "0x07", "info": "d"},
    {"js": " 69", "hid": "0x08", "info": "e"},
    {"js": " 70", "hid": "0x09", "info": "f"},
    {"js": " 71", "hid": "0x0A", "info": "g"},
    {"js": " 72", "hid": "0x0B", "info": "h"},
    {"js": " 73", "hid": "0x0C", "info": "i"},
    {"js": " 74", "hid": "0x0D", "info": "j"},
    {"js": " 75", "hid": "0x0E", "info": "k"},
    {"js": " 76", "hid": "0x0F", "info": "l"},
    {"js": " 77", "hid": "0x33", "info": "m(0x10) -> semi-colon / ñ(0x33)"},
    {"js": " 78", "hid": "0x11", "info": "n"},
    {"js": " 79", "hid": "0x12", "info": "o"},
    {"js": " 80", "hid": "0x13", "info": "p"},
    {"js": " 81", "hid": "0x04", "info": "q(0x14) -> a(0x04)"},
    {"js": " 82", "hid": "0x15", "info": "r"},
    {"js": " 83", "hid": "0x16", "info": "s"},
    {"js": " 84", "hid": "0x17", "info": "t"},
    {"js": " 85", "hid": "0x18", "info": "u"},
    {"js": " 86", "hid": "0x19", "info": "v"},
    {"js": " 87", "hid": "0x1D", "info": "w(0x1A) -> z(0x1D)"},
    {"js": " 88", "hid": "0x1B", "info": "x"},
    {"js": " 89", "hid": "0x1C", "info": "y"},
    {"js": " 90", "hid": "0x1A", "info": "z(0x1D) -> w(0x1A)"},
    {"js": " 91", "hid": "0xE3", "info": "Windows Key / Left ⌘ / Chromebook Search key"},
    {"js": " 92", "hid": "0xE7", "info": "right window key"},
    {"js": " 93", "hid": "0xE7", "info": "Windows Menu / Right ⌘"},
    {"js": " 95", "hid": "0xF8", "info": "sleep"},
    {"js": " 96", "hid": "0x62", "info": "numpad 0"},
    {"js": " 97", "hid": "0x59", "info": "numpad 1"},
    {"js": " 98", "hid": "0x5A", "info": "numpad 2"},
    {"js": " 99", "hid": "0x5B", "info": "numpad 3"},
    {"js": " 100", "hid": "0x5C", "info": "numpad 4"},
    {"js": " 101", "hid": "0x5D", "info": "numpad 5"},
    {"js": " 102", "hid": "0x5E", "info": "numpad 6"},
    {"js": " 103", "hid": "0x5F", "info": "numpad 7"},
    {"js": " 104", "hid": "0x60", "info": "numpad 8"},
    {"js": " 105", "hid": "0x61", "info": "numpad 9"},
    {"js": " 106", "hid": "0x55", "info": "multiply"},
    {"js": " 107", "hid": "0x57", "info": "add"},
    {"js": " 108", "hid": "Unknown", "info": "numpad period (firefox)"},
    {"js": " 109", "hid": "0x56", "info": "subtract"},
    {"js": " 110", "hid": "0x63", "info": "decimal point"},
    {"js": " 111", "hid": "0x54", "info": "divide"},
    {"js": " 112", "hid": "0x3A", "info": "f1"},
    {"js": " 113", "hid": "0x3B", "info": "f2"},
    {"js": " 114", "hid": "0x3C", "info": "f3"},
    {"js": " 115", "hid": "0x3D", "info": "f4"},
    {"js": " 116", "hid": "0x3E", "info": "f5"},
    {"js": " 117", "hid": "0x3F", "info": "f6"},
    {"js": " 118", "hid": "0x40", "info": "f7"},
    {"js": " 119", "hid": "0x41", "info": "f8"},
    {"js": " 120", "hid": "0x42", "info": "f9"},
    {"js": " 121", "hid": "0x43", "info": "f10"},
    {"js": " 122", "hid": "0x44", "info": "f11"},
    {"js": " 123", "hid": "0x45", "info": "f12"},
    {"js": " 124", "hid": "0x68", "info": "f13"},
    {"js": " 125", "hid": "0x69", "info": "f14"},
    {"js": " 126", "hid": "0x6A", "info": "f15"},
    {"js": " 127", "hid": "0x6B", "info": "f16"},
    {"js": " 128", "hid": "0x6C", "info": "f17"},
    {"js": " 129", "hid": "0x6D", "info": "f18"},
    {"js": " 130", "hid": "0x6E", "info": "f19"},
    {"js": " 131", "hid": "0x6F", "info": "f20"},
    {"js": " 132", "hid": "0x70", "info": "f21"},
    {"js": " 133", "hid": "0x71", "info": "f22"},
    {"js": " 134", "hid": "0x72", "info": "f23"},
    {"js": " 135", "hid": "0x73", "info": "f24"},
    {"js": " 144", "hid": "0x53", "info": "num lock"},
    {"js": " 145", "hid": "0x47", "info": "scroll lock"},
    {"js": " 160", "hid": "0x23", "info": "^"},
    {"js": " 161", "hid": "0x1E", "info": "!"},
    {"js": " 163", "hid": "0x20", "info": "#"},
    {"js": " 164", "hid": "0x21", "info": "$"},
    {"js": " 165", "hid": "Unknown", "info": "ù"},
    {"js": " 166", "hid": "Unknown", "info": "page backward"},
    {"js": " 167", "hid": "Unknown", "info": "page forward"},
    {"js": " 168", "hid": "0xFA", "info": "refresh"},
    {"js": " 169", "hid": "Unknown", "info": "closing paren (AZERTY)"},
    {"js": " 170", "hid": "0x25", "info": "*"},
    {"js": " 171", "hid": "0x32", "info": "~ + * key"},
    {"js": " 172", "hid": "0x4A", "info": "home key"},
    {"js": " 173", "hid": "0x7F", "info": "minus (firefox), mute/unmute"},
    {"js": " 174", "hid": "0x81", "info": "decrease volume level"},
    {"js": " 175", "hid": "0x80", "info": "increase volume level"},
    {"js": " 176", "hid": "0xEB", "info": "next"},
    {"js": " 177", "hid": "0xEA", "info": "previous"},
    {"js": " 178", "hid": "0x78", "info": "stop"},
    {"js": " 179", "hid": "0x48", "info": "play/pause"},
    {"js": " 180", "hid": "Unknown", "info": "e-mail"},
    {"js": " 181", "hid": "0x7F", "info": "mute/unmute (firefox)"},
    {"js": " 182", "hid": "0x81", "info": "decrease volume level (firefox)"},
    {"js": " 183", "hid": "0x80", "info": "increase volume level (firefox)"},
    {"js": " 186", "hid": "0x30", "info": "semi-colon / ñ(0x33) -> close bracket / å(0x30)"},
    {"js": " 187", "hid": "0x2E", "info": "equal sign"},
    {"js": " 188", "hid": "0x10", "info": "comma(0x85) -> m(0x10)"},
    {"js": " 189", "hid": "0x2D", "info": "dash"},
    {"js": " 190", "hid": "0x36", "info": "period(0x37) -> comma(0x36)"},
    {"js": " 191", "hid": "0x37", "info": "forward slash / ç(0x38) -> period(0x37)"},
    {"js": " 192", "hid": "0x34", "info": "grave accent / ñ / æ / ö(0x35) -> single quote / ø / ä(0x34)"},
    {"js": " 193", "hid": "0x38", "info": "?, / or °"},
    {"js": " 194", "hid": "0x63", "info": "numpad period (chrome)"},
    {"js": " 219", "hid": "0x2D", "info": "open bracket(0x2F) -> dash(0x2D)"},
    {"js": " 220", "hid": "0x31", "info": "back slash"},
    {"js": " 221", "hid": "0x2F", "info": "close bracket / å^(0x30) -> (0x2F)"},
    {"js": " 222", "hid": "0x35", "info": "single quote / ø / ä(0x34) -> grave accent / ñ / æ / ö(0x35)"},
    {"js": " 223", "hid": "0x38", "info": "`(0x35) -> forward slash / ç(0x38)"},
    {"js": " 224", "hid": "0xE3", "info": "left or right ⌘ key (firefox)"},
    {"js": " 225", "hid": "Unknown", "info": "altgr"},
    {"js": " 226", "hid": "0x64", "info": "< /git >, left back slash"},
    {"js": " 230", "hid": "Unknown", "info": "GNOME Compose Key"},
    {"js": " 231", "hid": "Unknown", "info": "ç"},
    {"js": " 233", "hid": "Unknown", "info": "XF86Forward"},
    {"js": " 234", "hid": "Unknown", "info": "XF86Back"},
    {"js": " 240", "hid": "Unknown", "info": "alphanumeric"},
    {"js": " 242", "hid": "0x88", "info": "hiragana/katakana"},
    {"js": " 243", "hid": "Unknown", "info": "half-width/full-width"},
    {"js": " 244", "hid": "Unknown", "info": "kanji"},
    {"js": " 255", "hid": "Unknown", "info": "toggle touchpad"}
];